apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: piehr-staging

resources:
  - ../../base

patches:
  - path: ingress-patch.yaml
  - path: replicas-patch.yaml

commonLabels:
  environment: staging

images:
  - name: gcr.io/PROJECT_ID/api
    newTag: staging
  - name: gcr.io/PROJECT_ID/web
    newTag: staging
  - name: gcr.io/PROJECT_ID/temporal-worker
    newTag: staging

