apiVersion: v1
kind: ResourceQuota
metadata:
  name: piehr-quota
  namespace: piehr
spec:
  hard:
    requests.cpu: "100"
    requests.memory: "200Gi"
    limits.cpu: "200"
    limits.memory: "400Gi"
    pods: "100"
    services: "50"
    persistentvolumeclaims: "10"
    secrets: "50"
    configmaps: "50"

