apiVersion: v1
kind: ServiceAccount
metadata:
  name: api-service-account
  namespace: piehr
  labels:
    app: api
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: web-service-account
  namespace: piehr
  labels:
    app: web
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: postgresql-service-account
  namespace: piehr
  labels:
    app: postgresql
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: redis-service-account
  namespace: piehr
  labels:
    app: redis
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: temporal-service-account
  namespace: piehr
  labels:
    app: temporal-worker

