apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: piehr

resources:
  - ../../base

patches:
  - path: ingress-patch.yaml
  - path: resource-quotas-patch.yaml

commonLabels:
  environment: production

images:
  - name: gcr.io/PROJECT_ID/api
    newTag: latest
  - name: gcr.io/PROJECT_ID/web
    newTag: latest
  - name: gcr.io/PROJECT_ID/temporal-worker
    newTag: latest

