apiVersion: v1
kind: ResourceQuota
metadata:
  name: piehr-quota
  namespace: piehr
spec:
  hard:
    requests.cpu: "200"
    requests.memory: "400Gi"
    limits.cpu: "400"
    limits.memory: "800Gi"
    pods: "200"
    services: "100"
    persistentvolumeclaims: "20"
    secrets: "100"
    configmaps: "100"

